# Generated by Django 5.2.1 on 2025-08-02 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_alter_customer_debt_alter_customer_email_and_more'),
        ('inventory', '0004_attributetype_sizechart_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Общая сумма продаж')),
                ('total_transactions', models.PositiveIntegerField(default=0, verbose_name='Количество транзакций')),
                ('total_items_sold', models.PositiveIntegerField(default=0, verbose_name='Количество проданных товаров')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод'), ('card', 'Карта'), ('debt', 'В долг')], max_length=20, verbose_name='Метод оплаты')),
            ],
            options={
                'verbose_name': 'Сводка по продажам',
                'verbose_name_plural': 'Сводки по продажам',
                'ordering': ['-date'],
                'unique_together': {('date', 'payment_method')},
            },
        ),
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Сумма покупок')),
                ('transaction_count', models.PositiveIntegerField(default=0, verbose_name='Количество транзакций')),
                ('debt_added', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Добавлено долга')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='customers.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Аналитика клиента',
                'verbose_name_plural': 'Аналитика клиентов',
                'ordering': ['-date'],
                'unique_together': {('customer', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('quantity_sold', models.PositiveIntegerField(default=0, verbose_name='Продано единиц')),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Выручка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='inventory.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Аналитика товара',
                'verbose_name_plural': 'Аналитика товаров',
                'ordering': ['-date'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
