# Generated by Django 5.2.1 on 2025-08-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_sender", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sms_template",
            name="content",
            field=models.TextField(
                help_text="Содержимое SMS-шаблона. Доступные переменные: @ - имя покупателя, $ - сумма долга"
            ),
        ),
    ]
