# Generated by Django 5.2.4 on 2025-07-16 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_productbatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productbatch',
            options={'ordering': ['expiration_date', 'created_at'], 'verbose_name': 'Партия товара', 'verbose_name_plural': 'Партии товаров'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория товара', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Остаток на складе', 'verbose_name_plural': 'Остатки на складе'},
        ),
        migrations.AddField(
            model_name='productbatch',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='supplier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Штука'), ('kg', 'Килограмм'), ('liter', 'Литр'), ('pack', 'Упаковка')], default='piece', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'barcode'], name='inventory_p_name_6d311d_idx'),
        ),
    ]
