# Generated by Django 5.2.1 on 2025-08-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_attributetype_sizechart_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='products', to='inventory.sizeinfo', verbose_name='Размеры'),
        ),
    ]
