# Generated by Django 5.2.1 on 2025-08-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeinfo',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=50, verbose_name='Размер'),
        ),
    ]
