# Generated by Django 5.2.1 on 2025-08-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_sizeinfo_product_alter_sizeinfo_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sizeinfo',
            unique_together={('size',)},
        ),
        migrations.RemoveField(
            model_name='sizeinfo',
            name='product',
        ),
    ]
