# Generated by Django 5.2.1 on 2025-08-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_product_size_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.IntegerField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Штрих-код'),
        ),
    ]
