# Generated by Django 5.2.1 on 2025-08-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_label',
            field=models.ImageField(blank=True, null=True, upload_to='product_labels/', verbose_name='Изображение этикетки'),
        ),
    ]
