# Generated by Django 5.2.1 on 2025-08-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_image_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Поставщик'),
        ),
    ]
