# Generated by Django 5.2.1 on 2025-08-06 09:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название единицы измерения')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('kind', models.CharField(choices=[('PRODUCT', 'Товар'), ('MATERIAL', 'Материал'), ('SERVICE', 'Услуга')], default='MATERIAL', max_length=20, verbose_name='Тип (товар/материал/услуга)')),
                ('short_name', models.CharField(blank=True, max_length=20, verbose_name='Короткое наименование')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('decimal_places', models.PositiveIntegerField(default=2, verbose_name='Количество цифр после точки')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.unitchoice', verbose_name='Единица измерения'),
        ),
    ]
