# Generated by Django 5.2.1 on 2025-08-08 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_unitchoice_alter_productbatch_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('m', 'Метр'), ('cm', 'Сантиметр'), ('mm', 'Миллиметр'), ('inch', 'Дюйм'), ('kg', 'Килограмм'), ('g', 'Грамм'), ('l', 'Литр'), ('pcs', 'Штука'), ('pack', 'Упаковка')], max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.unit', verbose_name='Единица измерения'),
        ),
        migrations.DeleteModel(
            name='UnitChoice',
        ),
    ]
