# Generated by Django 5.2.1 on 2025-08-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_unit_alter_product_unit_delete_unitchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='decimal_places',
            field=models.PositiveIntegerField(default=2, help_text='Количество знаков после запятой для этой единицы измерения'),
        ),
    ]
