# Generated by Django 5.2.1 on 2025-08-13 07:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_unit_decimal_places"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unit",
            options={
                "verbose_name": "Единица измерения",
                "verbose_name_plural": "Единицы измерения",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создан пользователем",
            ),
        ),
        migrations.AddField(
            model_name="productbatch",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.sizeinfo",
                verbose_name="Размер",
            ),
        ),
        migrations.AlterField(
            model_name="productbatch",
            name="quantity",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0001"))
                ],
                verbose_name="Количество",
            ),
        ),
    ]
