# Generated by Django 5.2.1 on 2025-07-19 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_name_customer_full_name_customer_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Долг'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Бонусные баллы'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Всего потрачено'),
        ),
    ]
