# Generated by Django 5.2.4 on 2025-07-17 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод'), ('card', 'Карта'), ('debt', 'В долг')], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создана'), ('completed', 'Завершена'), ('refunded', 'Возвращена')], max_length=50)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='sales.transaction')),
            ],
            options={
                'verbose_name': 'История продажи',
                'verbose_name_plural': 'История продаж',
                'ordering': ['-created_at'],
            },
        ),
    ]
