# Generated by Django 5.2.1 on 2025-08-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_transaction_payment_method_transactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='sell_unit',
            field=models.CharField(blank=True, help_text='Единица измерения для продажи (если отличается от базовой единицы товара)', max_length=10, null=True),
        ),
    ]
